name: Create cache on cachix

on:
  push:
    branches: [master]

jobs:
  cache:
    environment:
      name: cachix
      url: https://app.cachix.org/cache/${{ vars.CACHIX_CACHE_NAME }}#pull
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jlumbroso/free-disk-space@v1.3.1
        if: matrix.os == 'ubuntu-latest'
        with:
          large-packages: false  # Too slow
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --option accept-flake-config true
      - run: nix flake check --option accept-flake-config true
