name: Create cache on cachix
on:
  push:
    branches: [master]
jobs:
  cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: aiotter
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --option accept-flake-config true
      - run: nix flake check --option accept-flake-config true
